pkg/xattr

syscall_darwin.go
xattr_darwin.go
xattr_test.go

Hi, and thanks for providing this library! I'm using it for [restic](https://github.com/restic/restic), a secure, fast and deduplicated backup program.
We've recently discovered that under some circumstances, `Listxattr()` on Darwin seems to return an error with `errno` set to zero, e.g. here: https://travis-ci.org/restic/restic/jobs/202245770#L138
Looking at the source code, the other functions check for `errno != 0` and only then return an error: https://github.com/pkg/xattr/blob/master/syscall_darwin.go#L13
It seems this check is missing for `listxattr()`.
A demo program can be found here: https://gist.github.com/11156f3d7cc5af48b9a5b654e872c2dc
For a file `foo` without extended attributes this prints the following:
```
$ go run main.go foo
[] &xattr.XAttrError{Op:"listxattr", …
```

listxattr: Test errno != 0 before returning error

---

.travis.yml

This PR corrects the call to `goimports`, which is currently called with a non-existing directory:
```
The command "go test" exited with 0.
0.01s$ diff <(GOPATH="$PWD:$PWD/vendor" goimports -d ./src) <(printf "")
stat ./src: no such file or directory
```

Travis: fix directory for goimports

---

README.md
xattr.go
xattr_darwin.go
xattr_flags_test.go
xattr_linux.go
xattr_test.go

This allows the client code to specify the `flags` parameter, that was previously zeroed.

Added passing of the flags parameter to the lower-level syscall

---

xattr_flags_test.go

Check that XATTR_CREATE and XATTR_REPLACE fail
when they should (they do, everything seems to work fine).
Tested on Linux and MacOS High Sierra.

Add more testcases for SetWithFlags

---

go.mod
xattr.go
xattr_darwin.go
xattr_freebsd.go
xattr_linux.go
xattr_test.go

In unix, there is a possibility to create files without a path, for example by using `O_TMPFILE` flag in [open(2)](http://man7.org/linux/man-pages/man2/open.2.html).
This change adds a set of "F" variants to all functions that accepts a file descriptor instead of a path.
Only implemented for Linux, all other platforms use `Name()` call on a file to get its path.

Support "F" variants of operations (on file descriptors)

---

xattr_darwin.go

golang.org/x/sys/unix provides these for darwin as well now, so use them
instead of open-coding the syscalls.

Use x/sys/unix for lgetxattr, lsetxattr, lremovexattr and llistxattr on darwin

---

README.md
xattr_bsd.go
xattr_test.go

NetBSD uses the same syscalls as FreeBSD so it's easy to support
it using the existing implementation for FreeBSD.

Add NetBSD support

---

.travis.sh
.travis.yml
xattr_unsupported.go

To fix https://travis-ci.org/minio/mc/jobs/511289483 
```
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:40:10: undefined: getxattr
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:47:10: undefined: lgetxattr
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:54:10: undefined: fgetxattr
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:106:12: undefined: setxattr
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:115:12: undefined: lsetxattr
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:123:12: undefined: fsetxattr
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:132:12: undefined: setxattr
..\..\..\..\pkg\mod\github.com\pkg\xattr@v0.4.0\xattr.go:141:12: undefined: lsetxattr …
```

Fix windows and unsupported platform builds with dummy values

---

xattr_bsd.go
xattr_darwin.go
xattr_linux.go
xattr_unsupported.go

This will be useful for [us](https://github.com/thought-machine/please) so we can determine whether we need to fall back to a file based approach when they're not supported.

Added constant for whether xattrs are supported by the current platform

---

xattr_linux.go
xattr_linux_test.go

On Linux, system calls on some filesystems (CIFS, FUSE) can return EINTR when interrupted by signal handlers. Since the introduction of goroutine preemption in Go 1.14, these interruptions have become very common (e.g., restic/restic#2968). This patch handles them the same way the stdlib will do in Go 1.16 (golang/go@6b420169d798c7ebe733487b56ea5c3fa4aab5ce), by looping until the EINTR goes away.

Loop on EINTR on Linux

---

README.md
xattr_flags_test.go
xattr_solaris.go
xattr_test.go
xattr_unsupported.go

This adds support for solaris and illumos.  Setting extended attributes on symlinks is not supported on these platforms so the symlink functions return ENOTSUP and the symlink tests are skipped.  All other tests pass.

Add support for solaris (and illumos).

---

xattr_linux.go

This was already suggested in #52 and #53 with the aim of restoring Go 1.11 compatibility. That may not work, but omitting errors.Is does allow Go 1.16 to inline ignoringEINTR at every call site.

Check for EINTR with != on Linux

---

xattr.go

Fixes https://github.com/pkg/xattr/issues/58

Skip empty fields in Error()

---

xattr_solaris.go

Closing the fd's in this code after using them to create new os.File objects results in the fd being closed twice with disastrous results in multi-threaded code.  os.File already arranges for its finalizer to close the fd.
Found via restic tests.

Fix closing file descriptors twice

---

xattr_unsupported.go

If we want to use the `xattr.ENOATTR` safely in projects, we also need to define it for the unsuported Operating systems to make the compiler happy.

add alias to unsupported

---

xattr.go

This makes `xattr.Error` implement the `Unwrap` interface. It allows consumers to inspect the errors more efficiently like:
```go
_, err := xattr.Get("file", "attribute")
if err != nil {
if errors.Is(err, fs.ErrNotFound) {
//Do something
}
}
```

Make xattr.Error implement Unwrap

---

xattr_solaris.go

Fixes https://github.com/pkg/xattr/issues/67

(Solaris) return ENOTSUP on unix.Openat error

---

.github/workflows/build.yml
xattr_unsupported.go

ENODATA may not be defined use a dummy value from netbsd errno

syscall.ENODATA is not defined on unsupported OS

---

xattr_solaris.go
xattr_test.go

On Solaris, files need to be opened to obtain or change their attributes. But opening a FIFO file causes the calling thread to block until the write end is opened. Files are now opened using O_NONBLOCK to prevent this from happening.
Should fix restic/restic#4003.
Also fix comment on stringsFromByteSlice.
This code compiles, but I've not been able to test it without access to a Solaris box. I'm hoping @andy-js, @gco, and/or @racingmars can review/test this.

Fix FIFO handling on Solaris

---

xattr.go

Without this, we fail to fetch any attr larger than 1 KB.
Motivation: enable restic to back up Mac resource forks on NAS volumes. Currently, it loses data with only an easy-to-miss stderr message.
Unfortunately, TrueNAS doesn't document this different anywhere, if indeed it's their fault, but it's empirically what happens. This is on an OpenZFS volume with the `xattr=sa` property.
Thanks!

Detect the need to increase buffer size on TrueNAS SCALE.
